import type { Metadata } from "next";
// import localFont from "next/font/local";
// import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700", "800", "900"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    <html lang="en">
      {/* className={poppins.className} */}
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
